### ISSUE TITLE
Indentation is incorrect within media query

### ISSUE THREAD

**Issue by robinvdvleuten** [codekirei/postcss-prettify#4]
When I parse the folllowing string;

```css
@media (min-width: 576px) {.foo, .bar {color: #000}
```

It outputs only the first selector with the correct indentation;

```css
@media (min-width: 576px) {
  .foo,
.bar {
    color: #000;
  }
}
```
